name: mafalda_bot_tw

on:
  schedule:
    - cron: 30 6,10,14,17,19,21 * * *  #  Runs every 30th minute past the 6, 10, 14, 17, 19 and 21th hour 

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64' 

    - name: Install dependencies
      run: pip install -r requirements.txt
           
    - name: Run bot
      run: python main.py
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
